name: "Push Archery dependencies to Cachix"
on:
  schedule:
    - cron: "0 2 * * *"
  pull_request:
    paths:
      - .github/workflows/archery.yml
      - haskell/other/archery**
  push:
    paths:
      - .github/workflows/archery.yml
      - haskell/other/archery**
  workflow_dispatch:
jobs:
  push-to-cachix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: dandart
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        cd haskell/archery
        nix-build
        nix-store -qR --include-outputs $(nix-instantiate shell.nix --add-root result/shell --indirect) | cachix push dandart
